-- Enum types
do $$
begin
  create type public.user_role_enum as enum ('guru', 'siswa');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.project_group_progress_enum as enum ('process', 'revision', 'finish');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.group_member_role_enum as enum ('leader', 'member');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.discussion_session_status_enum as enum ('pending', 'process', 'finish');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.discussion_session_type_enum as enum ('online', 'offline');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.participant_score_enum as enum ('very good', 'good', 'enough', 'less', 'very less');
exception
  when duplicate_object then null;
end $$;

-- Shared trigger to keep updated_at in sync
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Core tables
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null,
  email text not null unique,
  email_verified_at timestamptz,
  role public.user_role_enum not null default 'siswa',
  password text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_profile (
  id bigint generated by default as identity primary key,
  id_user bigint not null unique,
  profile_picture text,
  birthday date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profile_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

create table if not exists public.project (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title text not null,
  description text,
  due_date date,
  file text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_user_id_fkey
    foreign key (user_id)
    references public.users (id)
    on delete cascade
);

create table if not exists public."merge" (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint merge_user_id_fkey
    foreign key (user_id)
    references public.users (id)
    on delete cascade
);

create table if not exists public.merged_project (
  id bigint generated by default as identity primary key,
  id_merge bigint not null,
  id_project bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint merged_project_id_merge_fkey
    foreign key (id_merge)
    references public."merge" (id)
    on delete cascade,
  constraint merged_project_id_project_fkey
    foreign key (id_project)
    references public.project (id)
    on delete cascade
);

create table if not exists public.project_group (
  id bigint generated by default as identity primary key,
  id_project bigint not null,
  name text not null,
  icon text,
  progres public.project_group_progress_enum not null default 'process',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_group_id_project_fkey
    foreign key (id_project)
    references public.project (id)
    on delete cascade
);

create table if not exists public.group_member (
  id bigint generated by default as identity primary key,
  id_project_group bigint not null,
  id_user bigint not null,
  role public.group_member_role_enum not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint group_member_id_project_group_fkey
    foreign key (id_project_group)
    references public.project_group (id)
    on delete cascade,
  constraint group_member_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

create table if not exists public.discussion_session (
  id bigint generated by default as identity primary key,
  id_project_group bigint not null,
  title text not null,
  date date not null,
  status public.discussion_session_status_enum not null default 'pending',
  type public.discussion_session_type_enum not null default 'online',
  discussion_result text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint discussion_session_id_project_group_fkey
    foreign key (id_project_group)
    references public.project_group (id)
    on delete cascade
);

create table if not exists public.participant (
  id bigint generated by default as identity primary key,
  id_discussion_session bigint not null,
  id_user bigint not null,
  join_at timestamptz not null default now(),
  leave_at timestamptz,
  constraint participant_id_discussion_session_fkey
    foreign key (id_discussion_session)
    references public.discussion_session (id)
    on delete cascade,
  constraint participant_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

create table if not exists public.discussion_chat (
  id bigint generated by default as identity primary key,
  id_discussion_session bigint not null,
  id_user bigint not null,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint discussion_chat_id_discussion_session_fkey
    foreign key (id_discussion_session)
    references public.discussion_session (id)
    on delete cascade,
  constraint discussion_chat_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

create table if not exists public.participant_score (
  id bigint generated by default as identity primary key,
  id_discussion_session bigint not null,
  id_user bigint not null,
  score public.participant_score_enum not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint participant_score_id_discussion_session_fkey
    foreign key (id_discussion_session)
    references public.discussion_session (id)
    on delete cascade,
  constraint participant_score_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

create table if not exists public.progress_discussion (
  id bigint generated by default as identity primary key,
  id_discussion_session bigint not null,
  id_user bigint not null,
  document text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint progress_discussion_id_discussion_session_fkey
    foreign key (id_discussion_session)
    references public.discussion_session (id)
    on delete cascade,
  constraint progress_discussion_id_user_fkey
    foreign key (id_user)
    references public.users (id)
    on delete cascade
);

-- Helpful indexes for FK columns
create index if not exists idx_user_profile_id_user on public.user_profile (id_user);
create index if not exists idx_project_user_id on public.project (user_id);
create index if not exists idx_merge_user_id on public."merge" (user_id);
create index if not exists idx_merged_project_id_merge on public.merged_project (id_merge);
create index if not exists idx_merged_project_id_project on public.merged_project (id_project);
create index if not exists idx_project_group_id_project on public.project_group (id_project);
create index if not exists idx_group_member_id_project_group on public.group_member (id_project_group);
create index if not exists idx_group_member_id_user on public.group_member (id_user);
create index if not exists idx_discussion_session_id_project_group on public.discussion_session (id_project_group);
create index if not exists idx_participant_id_discussion_session on public.participant (id_discussion_session);
create index if not exists idx_participant_id_user on public.participant (id_user);
create index if not exists idx_discussion_chat_id_discussion_session on public.discussion_chat (id_discussion_session);
create index if not exists idx_discussion_chat_id_user on public.discussion_chat (id_user);
create index if not exists idx_participant_score_id_discussion_session on public.participant_score (id_discussion_session);
create index if not exists idx_participant_score_id_user on public.participant_score (id_user);
create index if not exists idx_progress_discussion_id_discussion_session on public.progress_discussion (id_discussion_session);
create index if not exists idx_progress_discussion_id_user on public.progress_discussion (id_user);

-- updated_at triggers
drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_profile_updated_at on public.user_profile;
create trigger trg_user_profile_updated_at
before update on public.user_profile
for each row execute function public.set_updated_at();

drop trigger if exists trg_project_updated_at on public.project;
create trigger trg_project_updated_at
before update on public.project
for each row execute function public.set_updated_at();

drop trigger if exists trg_merge_updated_at on public."merge";
create trigger trg_merge_updated_at
before update on public."merge"
for each row execute function public.set_updated_at();

drop trigger if exists trg_merged_project_updated_at on public.merged_project;
create trigger trg_merged_project_updated_at
before update on public.merged_project
for each row execute function public.set_updated_at();

drop trigger if exists trg_project_group_updated_at on public.project_group;
create trigger trg_project_group_updated_at
before update on public.project_group
for each row execute function public.set_updated_at();

drop trigger if exists trg_group_member_updated_at on public.group_member;
create trigger trg_group_member_updated_at
before update on public.group_member
for each row execute function public.set_updated_at();

drop trigger if exists trg_discussion_session_updated_at on public.discussion_session;
create trigger trg_discussion_session_updated_at
before update on public.discussion_session
for each row execute function public.set_updated_at();

drop trigger if exists trg_discussion_chat_updated_at on public.discussion_chat;
create trigger trg_discussion_chat_updated_at
before update on public.discussion_chat
for each row execute function public.set_updated_at();

drop trigger if exists trg_participant_score_updated_at on public.participant_score;
create trigger trg_participant_score_updated_at
before update on public.participant_score
for each row execute function public.set_updated_at();

drop trigger if exists trg_progress_discussion_updated_at on public.progress_discussion;
create trigger trg_progress_discussion_updated_at
before update on public.progress_discussion
for each row execute function public.set_updated_at();
